---
- name: Unstall Grafana
  hosts: Hosts
  become: yes

  tasks:
    - name: Get apt key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
        state: absent
    - name: remove Grafana repo
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        filename: grafana
        state: absent
    - name: uninstall Grafana
      apt:
        name: grafana
        state: absent

   