---
- name: bootstrap main node
  hosts: Servers
  become: yes
  vars:
    listen_address: 0.0.0.0
    listen_port: 9090

  tasks:
    - name: Get apt key for grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
    - name: add Grafana repo
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        filename: grafana
        state: present
    - name: update apt cache amd install
      apt:
        name: grafana
        update_cache: yes
    - name: ensure Grafana is started and enabled
      systemd:
        name: grafana-server
        enabled: yes
        state: started        
    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /home/ubuntu
    - name: Extract Prom
      unarchive:
        src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
        dest: /home/ubuntu/
        remote_src: yes
    - name: Create Prom group
      group:
        name: prometheus
        state: present
    - name: Create prom user
      user:
        name: prometheus
        groups: prometheus
        shell: /sbin/nologin
    - name: Create prom directories
      file: 
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /etc/prometheus
        - /etc/prometheus/rules
        - /etc/prometheus/rules.d
        - /etc/prometheus/files_sd
        - /var/lib/prometheus
    - name: copy files to direct
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: prometheus
        group: prometheus
      loop:
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool        
    - name: copy more files to directory
      copy:
        src: "{{ item }}"
        dest: /etc/prometheus
        remote_src: yes
      loop:
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles
        - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries      
    - name: create config file
      template:
        src: prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
    - name: create SystemD file
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
    - name: ensure Prom is running
      systemd:
        name: prometheus
        enabled: yes
        state: started
    - name: install nginx
      apt: 
        name: nginx
        state: latest
    - name: Create IdleGame directories
      file: 
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: prometheus
        group: prometheus
        mode: '0755'
      loop:
        - /var/www/IdleGameWeb
        - /var/www/IdleGameWeb/Build
        - /var/www/IdleGameWeb/TemplateData
        - /var/www/IdleGameWeb/StreamingAssets
        - /var/www/IdleGameWeb/StreamingAssets/2DAnimationSampleAssetBundles
     
    - name: copy files to direct
      copy:
        src: "{{ item }}"
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: prometheus
        group: prometheus
      loop:
        - ~//index.html
              

    - name: start nginx
      systemd:
        name: nginx
        enabled: yes
        state: started        

        
